db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: dev
        POSTGRES_USER: dev
        POSTGRES_DB: treeApp
ginko:
    build: .
    links:
        - db
    environment:
        - PGHOST=db
        - PGDATABASE=treeApp
        - PGUSER=dev
    ports: 
        - "1337:1337"
    volumes: 
        - "./api:/usr/src/app/api"
        - "./assets:/usr/src/app/assets"
        - "./config:/usr/src/app/config"
        - "./private_images:/usr/src/app/private_images"
        - "./tasks-gulp:/usr/src/app/tasks-gulp"
        - "./test:/usr/src/app/test"
        - "./views:/usr/src/app/views"
        